import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/partials/Navbar";
import Footer from "@/components/partials/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SamurAi - Cyber Security",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-900 overflow-x-hidden`}>
        <Navbar />
        <div className="text-white">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
